### ISSUE TITLE
Initial properties list.

### ISSUE THREAD

**Issue by SamanthaFoxxx** [enriquemorenotent/unity-conversa-support#2]
The ability to automatically setup initial properties which should be created for any conversation instance.

Now for realize it need to go `ConversaGraphView.Load()`
Then init `var testBool = Activator.CreateInstance(typeof(BooleanProperty), "TestBool") as BaseProperty;` 
and add to list `conversation.AddProperty(testBool);`

**Comment by enriquemorenotent** [comment]
Fixed in 1.0.4
